### ISSUE TITLE
Qt Warning

### ISSUE THREAD

**Issue by sea-kg** [azadkuh/qhttp#23]
main.cpp:94:16: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 4 has type ‘std::chrono::duration<long int, std::ratio<1l, 1000l> >::rep {aka long int}’ [-Wformat=]
                );

**Comment by azadkuh** [comment]
thanx, there are such casting warning in sample codes (on some compilers), i'll cast them to resolve `-Wformat` warnings.

[ps. please also specify your compiler/os versions, sometimes 32/64bit systems issue different warnings for castings]

**Comment by sea-kg** [comment]
Ubuntu 16.04 (64 bit)

    $ qmake --version
    QMake version 3.0
    Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu

   $ g++ --version
   g++ (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
   Copyright (C) 2015 Free Software Foundation, Inc.
   This is free software; see the source for copying conditions.  There is NO
   warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Aztorius** [comment]
In example/keep-alive/main.cpp > Client::finalize()

**Comment by azadkuh** [comment]
fixed in [dev/b1876c](https://github.com/azadkuh/qhttp/commit/b18767cc3ea657a54811faedc0a382d7c743e2ef)

`clang++/OSX` and `g++/ubuntu` have different return type for `std::chrono::duration_cast<>()`
