### ISSUE TITLE
Do NOT change the case of HTTP (header) tags values.

### ISSUE THREAD

**Issue by iamazeem** [azadkuh/qhttp#27]
Hi,

IMO, the change of HTTP tags for comparison is fine but the values should remain intact.
For example, in case of custom headers the value may be a JSON object with strings in it.
I suggest that for all known headers it is okay to change the case (I can't think of a scenario where is should not) but for unknown headers it should NOT change the case.

Thanks!

~ AZEEM ~

**Comment by RafalNiewinski** [comment]
Already waiting in PR: #18

**Comment by iamazeem** [comment]
@RafalNiewinski : Thanks! :)
