### ISSUE TITLE
QHttpServer listening on path NOT working

### ISSUE THREAD

**Issue by iamazeem** [azadkuh/qhttp#28]
The server works fine when listening on a port e.g. `1234`. But, for a URI such as `http://localhost:1234/example`, it doesn't work.

Code snippet:
```
QHttpServer server { qApp };
server.listen ( "http://localhost:1234/example", ... );
```

Any suggestions?

**Comment by RafalNiewinski** [comment]
Because you can't use URI as listening interface.

You can listen on TCP port or UNIX socket or provide QHostAddress (http://doc.qt.io/qt-5/qhostaddress.html)

**Comment by iamazeem** [comment]
@RafalNiewinski 
Thanks for the `QHostAddress`. That solved the problem, actually.
I just looked at the other ctor of `QHttpServer` that takes host address along with port. 
```
bool listen( const QHostAddress& address,
                   quint16 port, 
                   const TServerHandler& handler = nullptr );

```
Sorry for using the wrong term "listening" on URI. I meant routing with URI.
