### ISSUE TITLE
QT_VERSION check fails

### ISSUE THREAD

**Issue by jslick** [azadkuh/qhttp#3]
qhttp does not build out-of-the-box for me on Qt 5.3.2 / G++.  The QT version check in qhttpabstracts.cpp seems backwards to me; am I missing something here?  I reversed the comparison and got it to compile.

**Comment by azadkuh** [comment]
oops!

you're right. it was a typo.
please pull new commit.

**Comment by jslick** [comment]
Yup, that does it!  That was fast.
