### ISSUE TITLE
qhttp seems to work just fine on Windows

### ISSUE THREAD

**Issue by oliviermaridat** [azadkuh/qhttp#4]
Hello,

FYI, I am using qhttp both on Linux and Windows 7 (32 and 64bits with a MingGW build), and it seems to work just fine on Windows.

Related to

> Tested under Linux (Ubuntu 12.04 LTS, 14.04 LTS, g++) and OS X (10.9/10.10, clang) and Windows7 (msvc 2013). Easily portable where ever Qt 5 works. I have no Windows machine (nor time, nor interest), but this lib should work just fine under Windows, although I've not tested it by myself.

**Comment by azadkuh** [comment]
thank you.

i will update the README.md
