### ISSUE TITLE
How to serve a folder using this?

### ISSUE THREAD

**Issue by etopian** [azadkuh/qhttp#5]
Any clue as how one can serve an entire folder, preferably recursively, using this framework?

Thanks.

**Comment by azadkuh** [comment]
hi,

by parsing [`QHttpRequest:url()`](https://github.com/azadkuh/qhttp/blob/master/src/qhttpserverrequest.hpp), one can read the requested file path, and simply copying the file content to the [`QHttpResponse`](https://github.com/azadkuh/qhttp/blob/master/src/qhttpserverresponse.hpp) will do the job as a dirty hack.
other features like resuming, transferring the large files, ... need further consideration.

In future, I will append a new `static file server` to the example/ folder.
