### ISSUE TITLE
Header: wrong date format

### ISSUE THREAD

**Issue by q3333q** [azadkuh/qhttp#7]
The 'M' in  'GMT' will be replaced with the Month.

https://github.com/azadkuh/qhttp/blob/master/src/qhttpserverresponse.cpp#L81
http://doc.qt.io/qt-5/qdatetime.html#toString

**Comment by azadkuh** [comment]
yupp! you're right
fixed by [#a94024c16d](https://github.com/azadkuh/qhttp/commit/a94024c16d34ad8df56a3f3fb49c43d95c83b169)
