### ISSUE TITLE
Crash on disconnect of empty connections

### ISSUE THREAD

**Issue by kintel** [azadkuh/qhttp#8]
I believe this is a bug:

Whenever a connection is closed, [```onDispatchRequest()```](https://github.com/azadkuh/qhttp/blob/master/src/private/qhttpserverconnection_private.hpp#L118) [will be called](https://github.com/azadkuh/qhttp/blob/master/src/private/qhttpserverconnection_private.hpp#L48).

In ```onDispatchRequest()```, you try to access ```ilastRequest```. The problem is that if no requests were sent, ilastRequest is NULL, and this causes a crash.

I find that such empty connections are made by browsers, and this bug crashes the server every time I request resource from a browser (only tested on Chrome on Mac).

To reproduce, I just run the hello world example: ```./xbin/helloworld  -p 8080 server```
..and send an empty connection: ```echo "" | telnet localhost 8080```

**Comment by kintel** [comment]
It might be sufficient to simply check for null, but I'm not familiar enough with the codebase to tell for sure:
```
if ( !ilastRequest || ilastRequest->d_func()->ireadState == QHttpRequestPrivate::ESent )
```

**Comment by azadkuh** [comment]
thank you so much for the report.
[commit: 016c2b7](https://github.com/azadkuh/qhttp/commit/016c2b71e61537a26f7215f6800f9624d8bc7bab)

**Comment by azadkuh** [comment]
maybe the [`std::enable_shared_from_this<>`](http://en.cppreference.com/w/cpp/memory/enable_shared_from_this) is a nicer approach than `QObject::deleteLater()` for this special domain.
