### ISSUE TITLE
Handle host inaccessability

### ISSUE THREAD

**Issue by evgeny-t** [azadkuh/qhttp#9]
Hi, 

When it tries to connect to the host that is unreachable, the app hangs.

For instance, if there is no web server running on `localhost`

```
client.request(qhttp::EHTTP_GET, QUrl("http://localhost"), 
    [](QHttpResponse* res) {
        res->collectData(128);
        res->onEnd([res]() {
            puts(res->collectedData().constData());
            puts("\n\n");
        });
    });
```
neither request handler or response handler are being called.

How should I handle the case when there is no server running on `http://localhost:80` or when `localhost` is unreachable?

Thanks!

**Comment by azadkuh** [comment]
well, `qhttp` uses Qt's event loop, so the program always remains in *waiting for new event/signal* mode.
the program does not hang, just waits in `app.exec()` for any other event.

you can simply apply a timer (or a single-shot timer) to check it:
```c++
   client.request(...) {...};
    QTimer timer;
    QObject::connect(&timer, &QTimer::timeout, []{
            qDebug("connection timed out!");
            QCoreApplication::quit(); // or what so ever that fits your logic
            });
    timer.start(5000); // mSec

    app.exec();
```

the `QHttpClient` also has a `setTimeOut(quint32)` for controlling the life-time of a ESTABLISHED connection.

**Comment by azadkuh** [comment]
a convenient connecting timer has been added to `QHttpClient`.

see sample code on main page: 
```cpp
client.request(...);
client.setConnectingTimeOut(10000, []{
    qDebug("connecting to HTTP server timed out!");
    QCoreApplication::quit();
});
```

**Comment by evgeny-t** [comment]
@azadkuh that's what I was looking for! Thank you!
